---
sudo: required
dist: trusty

matrix:
  include:
    # Remove temporarily 1.8, perhaps forever
    # - env: ANSIBLE_VERSION=1.8.4
    - env: ANSIBLE_VERSION=1.9.5
    # We don´t test 2.0.x series as they are very buggy
    - env: ANSIBLE_VERSION=2.1.2
    - env: ANSIBLE_VERSION=2.2.0

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-get -y install python-pip
 - sudo pip install ansible==$ANSIBLE_VERSION
 - ansible --version

script:
 - echo localhost > inventory
 - ansible-playbook -i inventory --connection=local --sudo -v test/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/